---
- name: Test Ansible Playbook
  hosts: local
  gather_facts: yes

  tasks:

    - name: Show hostname
      debug:
        msg: "Hostname is {{ ansible_hostname }}"

    - name: Show operating system
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distributin_version }}"

    - name: Create test file
      file:
        path: /tmp/github-actions-ansible.txt
        state: touch
        