name: Docker Self Hosted Test

on:
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Run hello-world container
        run: docker run --rm hello-world

      - name: Show running containers
        run: docker ps
        
      - name: Show all containers
        run: docker ps -a
      
#      - name: Clean Up
#       run: |
#          if [ "$(docker ps -q)" ]; then
#            docker stop $(docker ps -q)
#          fi

